(function(root) {
    var lang = 'fr',
        bundleName = 'main'  ;

    var lang_o = {
        topmenu: {
            BACK_HOME1:     "Retour en page d'accueil",
            BACK_HOME2:     "Ctrl+clic ou pression longue : réinitialisation de l'application",
            SKIP_TO_CONTENT:"Aller au contenu",
            MENU:           "Menu",
            LAUNCH_NEW_LANG:"Relancer l'application en",
            CONTACTS:       "Contacts",
            LEGALS:         "Mentions légales",//"Contacts",
            NEWS:           "Actualités",
            ABOUT:          "À propos...",
            PRESENTATION:   "Présentation",
            HOMEPAGE:       "Page d'accueil",
            TOPMENU:        "Menu général",
            FAVS0:          "Favoris",
            PREFS:          "Préférences",
            MYSPACE:        "Mon espace",
            LABEL_MY_SPACE: "Mon espace personnel",
            OBSERVATORIES:  "Observatoires",
            OBS_TITLE:      "Découvrez plus avec nos observatoires :"
        },

        actus: {
            DATE_PUB:   "Date de publication"
        },

        cookies: {
            I_UNDERSTAND:   "Je suis d'accord",//"Je comprends",
            I_UNDERSTAND_COOKIES: "Je comprends l'utilisation des cookies",
            I_REFUSE:   "Je refuse",
            I_REFUSE_COOKIES: "Je refuse l'utilisation des cookies non nécessaires",
            KNOW_MORE:      "En savoir plus",
            COOKIES_HINT:   "Ce site utilise des cookies pour réaliser des statistiques de visites.",
            OK_GA:          "J'autorise la mesure d'audience Google Analytics",
            OK_MA:          "J'autorise la mesure d'audience Matomo (ex-Piwik)",
            OK_AT:          "J'autorise la mesure d'audience AT Internet",
            HINT_GA :       "Google utilisera les informations de navigation dans le but d'évaluer votre utilisation du site mais ne recoupera pas votre adresse IP avec toute autre donnée détenue par Google."
                            +" Votre IP est anonymisée et vos informations supprimées après 14 mois. En cas d'autorisation, ce cookie expirera après 13 mois.",
            HINT_MA :       "Matomo est un outil de suivi de trafic recommandé par la Cnil (Commission Nationale de l'Informatique et des Libertés, France), particulièrement protecteur de vos données personnelles. Tel que configuré sur ce site, il ne requiert pas de consentement a priori, mais vous pouvez choisir de le désactiver."
                            +" Vos données personnelles ne sont pas transmises à une entreprise extérieure. Votre IP est anonymisée et vos informations supprimées après 13 mois. En cas d'autorisation, ce cookie expirera après 13 mois.",
            HINT_AT :       "AT Internet est un outil de suivi de trafic recommandé par la Cnil (Commission Nationale de l'Informatique et des Libertés, France), " +
                "particulièrement protecteur de vos données personnelles. Tel que configuré sur ce site, il ne requiert pas de consentement a priori, " +
                "mais vous pouvez choisir de le désactiver. Vos données personnelles ne sont pas transmises à une entreprise extérieure." +
                " Votre IP est anonymisée et vos informations supprimées après 13 mois. En cas d'autorisation, ce cookie expirera après 13 mois."
        },

        prefs:{
            //DRILLMAPS:"Changement automatique de niveau géographique<br>au zoom dans les cartes",
        },

        login:{
            LOGIN:              "S'identifier",
            LOGIN2:             "Identification",
            LOGIN_USER:         "Nom d'utilisateur",
            LOGIN_PWD:          "Mot de passe" ,
            LOGOUT:             "Déconnexion",
            WELCOME:            "Bienvenue",
            LOGOUT_RUNNING:     "Déconnexion en cours...",
            ERR_USER_MISSING:   "Erreur : nom d'utilisateur manquant",
            ERR_PWD_MISSING:    "Erreur : mot de passe manquant",
            IDENTIFYING:        "Identification en cours...",
            ERR_WRONG_CRED:     "Erreur : identification incorrecte",
            LOGIN_OK:           "Identification réussie",
            LOGOUT_OK:          "Déconnexion réussie",
            RESET:              "Mot de passe oublié ?",
            RESET_EMAIL:        "Email de l'utilisateur",
            ERR_EMAIL_MISSING:  "Email manquant",
            RESET_BUTTON:       "Envoi d'un email de réinitialisation",
            EMAIL_SUCCESS:      "Un email de réinitialisation a été envoyé. Merci de vérifier votre messagerie ainsi que vos courriers indésirables.",
            EMAIL_FORMAT:       "L'email saisi n'est pas entré avec un format reconnu.",
            RESET_WRONG_PWD:    "Les deux mots de passe saisis ne sont pas identiques.",
            RESET_SECURITY:     "Pour des raisons de sécurité, veuillez réutiliser le lien reçu depuis votre email.",
            RESET_SECURITY_MAIL:"La réinitialisation du mot de passe a échoué. Vérifiez le champ email. S'il est correct, cela veut dire que le formulaire a expiré. Dans ce cas, refaites une demande d'envoi de mail de réinitialisation.",
            RESET_WEAK_PWD:     "Le nouveau mot de passe saisi n'est pas valide. Il doit contenir au moins 12 caractères, au moins une minuscule, au moins une majuscule, au moins un caractère spécial.",
            RESET_SUCESS:       "Le mot de passe a été réinitialisé avec succès.",
            RESET_INSTRUCTIONS: "Afin de finaliser la demande de réinitilisation de mot de passe, veuillez resaisir votre email ainsi qu'un nouveau mot de passe. Ce nouveau mot de passe doit contenir au moins 12 caractères, au moins une minuscule, au moins une majuscule, au moins un caractère spécial.",
            EMAIl:              "Email",
            NEW_PASSWORD:       "Entrez un mot de passe",
            REPEAT_NEW_PASSWORD: "Re-tapez le mot de passe",
            SEND_PASSWORD:      "Réinitialiser",
            RESET_TITLE:        "Formulaire de réinitilisation du mot de passe"
        },

        home:{
            TAG_SELECT_HINT:    "Voir les indicateurs relatifs à ce mot-clé",
            GO_TO_THIS_MAP:     "Accéder à cette carte",
            GO_TO_THIS_REPORT:  "Accéder à ce rapport",
            GO_TO_THIS_INDIC:   "Voir l'indicateur",
            STOP_CAROUSEL:      "Arrêter le carrousel",
            RUN_CAROUSEL:       "Relancer le carrousel"
        },

        contacts: {
            CONTACT_US: "Nous contacter",
            CONTACT_BODY: "Pour toute question relative au contenu ou au mode d'emploi de ce site, contacter l'administrateur."
        },

        print: {
            MARGIN_STD    : 'Marge standard',
            MARGIN_LARGE  : 'Marge large (Firefox)',
            MARGIN_NARROW : 'Marge étroite (IE/Edge)',
            MARGIN_MINI   : 'Marge minimale (Chrome)',
            PORTRAIT:     "Portrait",
            LANDSCAPE:    "Paysage",
            PRINT_HINT:   "Pour imprimer, veuillez passer par le menu ACTIONS",
            USER_COMMENT: "commentaire entré par l'utilisateur",
            IMPORT_USER_WARNING: "Cette carte a été réalisée par l'utilisateur, à partir de données externes."
        },

        anim: {
            ANIM:           "Animation...",
            TEMP_ANIM:      "Animation temporelle",
            RUN_ANIM:       "Lancer le défilement",
            ANIM_PREPARING: "Préparation en cours",
            ANIM_LIMIT_NOTE: "Note : pour des raisons de performance, l'animation ne porte que sur les XX dernières périodes"
        },

        restit_menus: {
            MENU_ADDLAYERS:         "Ajouter des couches",
            MENU_ADDLAYERS_TITLE:   "Plans, photos, zonages...",//Habiller
            MENU_ETIQS:             "Étiqueter",
            MENU_EXPORT:            "Exporter, réutiliser",
            MENU_EXPORT_TITLE:      "Sauvegarder son travail, partager sur les réseaux sociaux...",
            MENU_SEARCHGEO_TITLE:   "Identifier un territoire, se géolocaliser...",
            MENU_PRINT_TITLE:       "Ajuster la mise en page avant impression ou export PDF"
        },

        mapthemes: {
            CHANGE_COLOURS:      "Changer les couleurs",
            DISPLAY_STROKES:     "Afficher les contours",
            ANALYSIS_OPACITY:    "Opacité de l'analyse",
            SPECIFY_THRESHOLDS:  "Déterminer les seuils",
            ROUND_THRESHOLDS:    "Arrondir les seuils",
            SIGNIFICANT_FIGURES: "chiffres significatifs",
            COMPUTE_ON_SEL:      "Calculer sur la sélection",
            ISOLATE_RANGES:      "Isoler des classes",
            DEFORMING_MAP:       "Déformer la carte",
            REFINE_LEGEND:       "Affiner la légende",
            EXTENDED_MODE:       "Mode étendu",
            SHOW_COUNTS:         "Afficher les effectifs de classe",
            ASCENDING:           "Ordre croissant des bornes",
            ADJUST_TO_DISTRIB:   "Calquer les seuils sur la distribution",
            MEM_SETTINGS:        "Mémoriser ces choix pour toutes les analyses",
            ISOLATE_CATEGS:      "Isoler des catégories",
            SYMBOL:              "Symbole",
            COLS_AUTO:           "Couleurs automatiques (meilleur contraste)",
            STROKE:              "contour",
            STROKES_AUTO:        "Contours automatiques",
            STROKE_WIDTH:        "épaisseur",
            FILL_MODE:           "Remplissage",
            ADJUST_SYMB_SIZE:    "Ajuster la taille des symboles",
            COMPUTATION_MODE:    "Mode de calcul",
            OPTIMAL:             "optimal",
            MAX:                 "taille max",
            CORRESP:             "correspondance",
            CUMULATED_AREA:      "surface cumulée",
            OF_TERRITORY:        "du territoire",
            SYMB_SIZE:           "taille du symbole",
            FOR_VALUE:           "pour la valeur",
            EASE_IF_STRONG_ZOOM: "Assouplir si fort changement de zoom",
            APPLY_TO_ALL_SYMB_ANALYSISES:  "Appliquer à toutes les analyses par symboles",
            APPLY_ADVANCED_TREATMENTS:     "Appliquer des traitements avancés",
            REFINE_RENDERING:    "Affiner le rendu",
            SHOW_FLUX_DIRECTION: "Marquer l'orientation (zoomer si besoin)",
            FLUX_ORDER_ASC: "Valeurs les plus élevées à l'avant-plan",
            FLUX_ARROW_POS: "Position de la flèche",
            FLUX_ARROW_POS_MIDDLE: "Millieu",
            FLUX_ARROW_POS_END: "Fin",
            FLUX_DRAW_BEND: "Dessiner des arcs",
            FLUX_BENDING_LEVEL: "Courbure",
            FLUX_BENDING_LOW:     "faible",
            FLUX_BENDING_INTERM:     "moyenne",
            FLUX_BENDING_HIGH:     "forte",
            LISS_SP:             "Lissage spatial",
            LISSED_DATA:         "Données lissées",

            ANAMORPH:       "Anamorphose",
            ANAMORPH_CHORO_HINT:  "Note : la déformation se fait à partir du numérateur",
            COL_PAL:        "Palettes de couleurs",
            CONTRASTED:     "plus contrastées",
            TWO_TINTS:       "2 teintes",
            CUSTOM_BREAKS:  "Seuils manuels",
            MANU:           "seuils manuels",
            QUANT:          "Quantiles",
            KMEANS:         "K-moyennes",
            JENKS:          "Seuils naturels (Jenks-Fisher)",
            NESTED_MEANS:   "Moyennes emboîtées",
            STDEV:          "Écarts types",
            DISTRIB:        "Distribution",
            DEM:            "Densité d'écart à la moyenne" ,
            RANGES:         "classes",
            METHOD:         "Méthode",
            DISPLAY_ALL:    "Tout afficher",
            VALREF_IS_BREAK:  "La valeur moyenne est un des seuils",
            DEFAULT_SETTINGS:  "Réglages par défaut",
            ADDITIONAL_TREATMENT:"Traitement additionnel",

            BIGGERSYMB_SIZE:    "Taille du symbole le + grand",
            OPACITY:            "Opacité",
            FILLED:             "plein",
            NOFILLED:           "contour",
            ASSOC_CHORO:        "Colorier les symboles avec un autre indicateur" ,
            HEAT_VERSION:       "Version lissée (carte de température)",
            DOT_VERSION:        "Version à densité de points",
            ADJUST_TO_SEL_R:    "Ajuster à la sélection",

            SPHERE:             "sphère",
            CIRCLE:             "rond",//"cercle",
            SQUARE:             "carré",
            STAR:               "étoile",
            TRIANGLE:           "triangle",
            CROSS:              "croix",
            LOSANGE:            "losange",

            ADJACENT_AREAS_DIFFERENT_COLOR: "2 territoires limitrophes ont une couleur différente",
            POLE_TYPO_DESC_LEGEND_MAIN: "Coloration par pôle",
            POLE_TYPO_DESC_LEGEND: "Coloration par pôle, 2 pôles limitrophes ont une couleur différente",

            DISPERSE :  "Dispersion des points superposés",  //NEW
            RADIUS: "rayon"  , //NEW
            NO_POSITIVE_VALUES: "absence de valeurs > 0",

            REPART_DISTRIB:         "Répartition - distribution"
        },

        exports: {
            IMG_EXPORTS:    "Exports image",
            PNG_EXPORT:     "Exporter la carte (format image, PNG)",
            SVG_EXPORT:     "Exporter la carte (format vectoriel, SVG)",
            PRINT_LAYOUT:   "Mettre en page pour imprimer ou générer un PDF",
            DATA_EXPORTS:   "Exports de données",
            DISPLAY_TABLE:  "Afficher le tableau de données",
            RELOAD_CONFIG:  "Conserver cette configuration",
            SOCIAL_NETWORKS:"Réseaux sociaux",
            SHARE_SOCIAL:   "Partager un lien direct sur des réseaux sociaux",
            FACEBOOK:       "Partager sur Facebook (nouvelle fenêtre)",
            TWITTER:        "Partager sur Twitter (nouvelle fenêtre)",
            GOOGLEP:        "Partager sur Google+ (nouvelle fenêtre)",
            LINKEDIN:       "Partager sur LinkedIn (nouvelle fenêtre)",
            MAIL:           "Partager par email",

            BACK_TO_CHART: "Retour graphique",
            TO_DATA: "Données",
            XP_HTML: "Export HTML",
            XP_SVG: "Export SVG",
            XP_PNG: "Export PNG",
            XP_DATA: "Export CSV",

            IFRAME: "Réutiliser",
            IFRAME_DESC: "Insérer le code HTML ci-dessous dans une page web pour y intégrer le graphique",
            IFRAME_COPY: "Copier",
            IFRAME_BACK: "Retour",
            IFRAME_NOT_AVAILABLE: "Ce graphique ne peut pas être réutilisé car il n'est pas public.",

            IFRAME_HINT: "Explorer ce contenu dans un nouvel onglet"
        },

        geo: {
            PLANS_PHOTOS:       "Plans et photos",
            HABILL:             "Couches d'habillage",
            STATLAYER_OPACITY:  "Opacité de la couche réactive",
            NO_BACKGROUND:      "Aucun arrière-plan",
            CITIES:             "Villes",
            OSM_STYLE_STD : "Style standard (Mapnik)",
            OSM_STYLE_STAMEN : "Style Stamen",
            OSM_STYLE_FRANCE : "Style France",
            OSM_STYLE_THUNDERFOREST : "Style Thunderforest"
        },

        etiqs: {
            ETIQS:              "Étiquettes",
            ETIQ:               "Étiqueter",
            DISPLAY_ETIQS:      "afficher les étiquettes",
            CONTROL_PLACEMENT:  "Contrôler le placement",
            OPTIMIZE:           "optimiser à l'intérieur des territoires",
            HIDE_OVERFLOW:      "masquer les textes qui débordent",
            BOLD:               "gras",
            ITALIC:             "italique",
            CAPS:               "maj.",
            HALO:               "halo",
            COLOUR:             "couleur",
            SIZE:               "taille",
            VISIBILITY:         "Visibilité",
            STYLE:              "Style",
            CONTENT:            "Contenu",
            ETIQ_EXCESS:        "trop d'étiquettes à dessiner, veuillez zoomer",
            LABELS_DRAWING:     "dessin en cours",
            SELONLY:            "sur la sélection seulement"
        },

        map: {
            OVERALL_VIEW:       "Vue d'ensemble",
            ZOOM_PLUS:          "Zoom +",
            ZOOM_MOINS:         "Zoom -",
            ZOOM_RECTANGLE:     "Zoom par rectangle",
            DRAW_ZOOM_RECT:     "Dessiner un rectangle de zoom. Esc pour annuler"
        },

        searchgeo: {
            SEARCH_GEO:         "Recherche géographique",
            GEOLOCALIZE:        "Se localiser",
            THIS_VIEW_ONLY:     "Dans cette vue seulement",
            LOAD_SAVED_SEL:     "Rappeler une sélection sauvegardée",
            LOAD_SAVED_SEL_S:   "Charger une sélection",
            TOPO_SEARCH:        "Recherche topologique",
            SEARCH_TERRITORIES: "Identifier des territoires",
            BORDERING:          "en bordure",
            ISOLATED:           "isolés",
            MULTIPARTS:         "en plusieurs parties",
            WITH_HOLES:         "présentant des trous",
            ONE_NEIGHBOUR:      "avec un seul voisin"
        },

        favs: {
            PANEL_TITLE:      "Favoris & études",
            SELECT_TYPE:      "Choisissez un type de favori",
            MANAGEMENT_HINT:  "Sélectionner un favori pour pouvoir le supprimer ou le déplacer dans la liste. Pour le charger, cliquer sur la flèche vers la droite.",
            LOAD_STUDY:       "Charger un fichier d'étude...",
            NO_SELGEO:        "Vous n'avez pas de territoire sauvegardé...",
            LOAD_SEGEO:       "Charger ce territoire",
            NO_MAP:           "Vous n'avez pas de carte sauvegardée...",
            LOAD_MAP :        "Charger cette carte",
            NO_REPORT:        "Vous n'avez pas de rapport sauvegardé...",
            GET_LINK:         "Obtenir un lien direct vers cette carte",
            LINK_HINT:        "Une URL paramétrée cible les indicateurs cartographiés dans la carte courante.",
            OPEN_NEW_WIN:     "Ouvrir dans une nouvelle fenêtre",
            SAVE:             "Placer dans les favoris",
            HINT:             "Outre les indicateurs de la carte courante, le favori conserve tous les indicateurs chargés, ainsi que la sélection géographique en cours.",
            SAVE_STUDY:       "Sauver une étude",
            STUDY_HINT:       "L'étude est partageable. Plus riche qu'un favori, elle comprend l'ensemble des jeux de données importés. Elle conserve également les reparamétrages des analyses.",
            NAME_STUDY:       "Nommer votre étude...",
            SAVE_TITLE:       "Sauver un favori",
            LOAD_TITLE:       "Charger un favori",
            MAPS_INDICS:      "Cartes et indicateurs",
            ERR_STUDY_NAME:   "Erreur : veuillez donner un nom à votre étude",
            OK_FAV_SAVE:      "Favori sauvegardé. Pour le recharger, visitez la section \"Favoris\" via l'icone \"Utilisateur\" du menu supérieur",
            WARNING_FAV_EXIST: "Ce favori est déjà sauvegardé.",
            OK_STUDY_SAVE:    "Etude sauvegardée. Pour la recharger, visitez la section \"Favoris\" via l'icone \"Utilisateur\" du menu supérieur",
            WARNING_PRIVATE:  "Attention : le mode privé/incognito  ne permet pas d'utiliser les préférences.",

            INSERT_IN_WEBPAGE:  "Intégrer dans une page web",
            ADD_IFRAME_CODE:    "Ajouter le code HTML ci-dessous dans votre page web"
        },

        selection: {
            DESELECT_ALL:       "Tout déselectionner",
            GOTO_REPORTS:       "Éditer des rapports",
            GOTO_REPORTS_HINT:  "Accéder à l'espace Rapports",
            SELECTIONS_HELP:    "Aide sur les sélections",
            SELECTIONS_HELP_HINT: "Aide sur les différentes façons de sélectionner un territoire",
            SEL_PLAY_WITH:  "Agir sur la sélection",
            SEL_PLAY_WITH2: "Agir sur cette sélection",
            SEL_PLAY_WITH2_HINT: "Étendre, sauvegarder, zoomer sur",
            MY_SELECTION:      "Ma sélection",
            SEL_THE:        "Sélectionner les",
            SEL_CLEAR:      "Effacer",// la sélection",
            SEL_ZOOM_IN:    "Zoomer sur",// la sélection",
            SEL_ZOOM_IN2:   "Zoomer sur la sélection",
            SEL_SAVE:       "Sauver la sélection géographique",
            SELGEOIMPORT_HINT: "Les codes géographiques que vous venez d'importer forment une sélection que vous pouvez conserver pour un usage ultérieur dans cet outil.",
            SELGEOIMPORT_HINT2: "Vous pouvez aussi examiner les rapports disponibles pour cette zone",
            SEL_SAVE_OK:    "Sélection sauvegardée. Pour la recharger, visitez la section &quot;Favoris&quot; du menu supérieur, ou ACTIONS / Rechercher",
            SEL_NAME:       "Nommer votre sélection",

            SEL_SYNTH_INFO: "Infos de synthèse",
            SEL_LONG_SERIES: "Séries longues",

            SEL_REPORTS:     "Rapports détaillés",
            SEL_EXTEND:      "Étendre la sélection",

            SEL_BROWSE_METHODS: "Parcourir les méthodes de sélection",
            SEL_DBLCLICK_HINT:  "pour une sélection simple et un appel direct de ce panneau",

            SEL_METHODS:        "Méthodes de sélection",

            SEL_CLICK_ON_MAP:   "Clic sur la carte",
            SEL_CLICK_HINT:     "pour une sélection simple",
            SEL_DBLCLICK_HINT2: "pour une sélection simple et un appel direct du panneau de gestion de la sélection",

            SEL_BY_ZON:         "Sélection par zonage",
            SEL_BY_ZON_HINT:    "ajouter un zonage (ACTIONS>Couches) et cliquer sur la carte. Dans le panneau d'information sur la sélection, cliquer sur le zonage englobant le territoire visé",
            SEL_CLEAR2:         "Désélectionner",
            SEL_CLEAR2_HINT:    "cliquer en dehors de la carte, fermer le panneau &quot;Ma sélection&quot; avec la croix ou presser D",

            MANUAL_SEL:         "Sélection manuelle",
            MANUAL_SEL_HINT:    "<b>Maj + clic ou pressions longues successives</b> pour sélectionner ou déselectionner plusieurs objets.",
            CIRC_SEL:           "<b>Sélection circulaire</b>",
            CIRC_SEL_HINT:      "pression longue sur le centre et glissement pour définir le rayon",
            PANEL_CUR_SEL:      "Sélection en cours",
            EXTEND_TERR:        "Pour ajuster votre territoire",//"Pour étendre votre territoire, choisissez",
            SELECT_SURROUNDING_ZONE: "Choisissez une zone englobante",//NEW
            USE_LAST_PRESSED:   "Utilisez le dernier objet cliqué",
            CIRC_SEL_HINT2:     "glisser pour sélection circulaire...",
            DEFINE_RADIUS:      "Définissez un rayon (à vol d'oiseau)",
            ISOLATE_SELECTION: "Isoler la sélection"
        },

        report: {
            BASE100_INDICE: "Indice base 100",
            TRAGE:          "Tranche d'âge",
            MEN:            "Hommes",
            WOMEN:          "Femmes",

            NOTSDIFF_AVG:   "Non significativement différent",
            PCTL25:         "1er quartile",//"percentile à 25%" ,
            PCTL75:         "3ème quartile",//"percentile à 75%",
            SWORST_AVG:     "Signific. - favorable",  //+ favorable
            SBETTER_AVG:    "Signific. + favorable",
            WORST:          "- favorable",
            BEST :          "+ favorable",
            AREA_VALUE :    "Valeur sélection",
            FILTER_SPINE_HINT : "Pressez une catégorie pour filtrer le diagramme",//"frPress a category to filter the diagram",
            SPINE_CHART_HEADER : "Schéma|\"Spine\"",//"Spine|chart",

            TEMPORAL_EVOL:  "Évolution temporelle",
            TEMPORAL_EVOL_COMP: "Évolution temporelle comparée",
            TEMPORAL_EVOL_CUMUL: "Évolution temporelle cumulée",
            REPART:         "Répartition",
            RANKING:        "classement",
            FIRST_TERRS:    "les XXX premiers",//territoires
            LAST_TERRS:     "les XXX derniers",//territoires
            FIRST_POLES:    "les XXX premiers pôles",
            LAST_POLES:     "les XXX derniers pôles",
            SELECTION_DETAIL: "détail de la sélection",
            NB_POLES:       "nb de pôles",
            EVOL_NB_POLES:  "Évolution du nb de pôles",
            LOCATED_IN:     "situés en", //NEW
            STUDY_ZONE:     "Zone d'étude",
            COMPAR_ZONE:    "Zone de comparaison",
            FLUX_IN:        "Flux entrants",
            FLUX_OUT:       "Flux sortants",
            FLUX_SOLDE:     "Solde entrées/sorties",
            EVOL_ABB:       "Évol.", //NEW,
            DISPLAY_ALL :   "Tout afficher",
            ISOLATE :       "Isoler",
            PRESMAP:        "Carte de présentation",
            NO_DATA_BLOCK : "Le graphique n'existe pas.",
            NO_DATA_CHAPTER : "Pas de contenu pour ce chapître.",
            LOADING_BLOCK : "Préparation de la data-visualisation..."
        },

        indics: {
            MINI:       "minimum",
            MAXI:       "maximum",
            POLE:       "pôle",
            POLES:      "pôle(s)",
            FIRST_POLE: "1er pôle",

            POSITIVE:   "positif",
            NEGATIVE:   "négatif",
            CATEG:      "Catégorie",
            CATEGS:     "catégories",

            NA:     "N/A",
            NAMQ:   "N/A - résultat non disponible",
            NASS:   "N/A - secret statistique",
            NAD0:   "N/A - division par 0",
            NAOLP:  "N/A - réponse non communiquée",
            NAZON:  "N/A - hors champ",
            VALMQ:  "valeur manquante",
            NAMQ_SHORT:   "N/A",
            NASS_SHORT:   "N/A Secret stat.",
            NASS_IND_SHORT: "N/A Secret stat. induit",
            NAD0_SHORT:   "N/A Div. par 0",
            NAOLP_SHORT:  "N/A Non communiquée",

            UNIT:         "Unité",
            PERIOD:       "Période",
            PERIODS:      "Périodes",
            SOURCE :      "Source",
            KEY_FIGURES:  "Chiffres-clés",

            INDIC_FOREFRONT:        "Premier plan (symboles)",
            INDIC_BACKGROUND:       "Arrière-plan (aplats de couleurs)",
            INDIC_ACTIVATE:         "Activer cet indicateur",
            INDIC_ACTIVATE_ON_MAP:  "Activer/désactiver cet indicateur de la carte",
            INDIC_DOC:              "Documentation de l'indicateur",
            INDIC_CLICK_TO_ACTIVATE:"Cliquer pour activer",

            INDIC_FORMULA:  "Formule",
            INDIC_FORMULA2: "Formule de calcul",

            LINK_MAP_INDIC: "Lien vers une cartographie de cet indicateur",
            SHOW_CAT_INDIC  :  "Afficher seulement cette catégorie",
            VARS :          "Variables",

            DATA_PRECISION : "Précision des données",  //NEW
            VALUES_WITH_CI : "Valeurs assorties d'un intervalle de confiance",
            DIFF_LIMITS :    "Limites de diffusibilité",
            VALS_NONDIFF :   "Valeurs non diffusibles et non exportables",
            VALS_NONEXP :    "Valeurs affichées mais non exportables",
            LCL_CI:         "borne inf. de l'IC",
            UCL_CI:         "borne sup. de l'IC",
            AREA_PROFILE:    "Profil de territoire"
        },

        concepts: {
            STUDIES:    "Études",
            REPORT:     "Rapport",
            REPORTS:    "Rapports",
            SHEET:      "Fiche",
            MAP:        "Carte",
            MAPS:       "Cartes",
            TABLE:      "Tableau",
            SYNTH:      "Synthèse",
            THEME :     "Thème",
            THEMES:     "Thèmes",
            THEMES2:    "Thème(s)",
            DATASET:    "Jeu de données",
            INDIC :     "Indicateur",
            INDICS:     "indicateur(s)",
            INDICS2:    "Indicateurs",
            EXTERNAL_DATA:  "Données externes",
            WORKSPACES:     "Espaces de travail",
            DATAVIZ:     "Data-visualisation",
            EXTENT:     "Étendue",
            EXTENTS:     "Étendue(s)",
            LEVEL:      "Niveau",

            SELECTION:  "Sélection",
            SELECTIONS: "Sélections",
            SELS_GEO:   "Sélections géographiques",

            TERRITORY:  "territoire",
            TERRITORIES:"Territoires",
            LAYERS:     "Couches",
            ZONING:     "Zonage",
            ZONINGS:    "Zonages",
            ZONE:       "Zone",

            NIVGEOS_S:  "Niveaux géos",
            NIVGEOS :   "Niveaux géographiques",
            NIVGEO :    "Niveau géographique",

            FLUX:       "Flux",

            INDIC_CU:   "ESPACE INDICATEURS",
            ZONAGE_CU:  "ESPACE ZONAGES",
            REPORT_CU:  "ESPACE RAPPORTS",
            EXTERNALDATA_CU: "ESPACE DONNÉES EXTERNES"
        },

        tables: {
            FILTER_TABLE:       "Filtrer le tableau",
            FILTER_TABLE_HINT:  "Le filtre porte sur le tableau uniquement. La sélection est reportée sur la carte et la fiche de synthèse.",
            EXPORT_DATA:        "Exporter les données",
            COPY_PREPARING:     "Préparation de la copie",
            COPY_COMPLETED:     "Copie réalisée dans le presse-papiers",
            COPY_HINT:          "Presser <i>Ctrl</i> ou <i>⌘</i> + <i>C</i> pour copier les données<br>vers le presse-papiers.",
            FULL_DATASET:       "tout le jeu de données",
            FILTERED_DATASET:   "le tableau filtré",
            FILTER_IN:          "Filtrer dans",
            CUR_SELECTION:      "la sélection courante",
            FORMATS:            "Formats",
            SELECT_FORMAT:      "Choisir un format",
            XLSX:               "Excel (xlsx)",
            ODS:                "Open Document (ods)",
            CSV:                "CSV",
            COPY_CLB:           "Copie dans le presse-papiers",
            PRINT_SCOPE:        "Champ de l'impression",
            PRINT_TABLE:        "Imprimer le tableau",
            FILTER_SCOPE:       "Champ du filtrage",
            FILTER_CRITS:       "Critères de filtrage",
            CODES_LIST:         "Liste de codes",
            NO_POLE:            "Aucun pôle",
            APPLY_FILTERS:      "Appliquer<br>les filtres",
            APPLY_FILTERS_AND_SELECT: "Appliquer les filtres<br> et sélectionner<br>le résultat",
            CLEAR_FILTERS:       "Effacer les filtres",
            CLEAR_SEL:           "Effacer la sélection courante",
            ADD_COLUMN:          "Ajouter une colonne",
            TABLE_CONTENT_HINT:  "Le tableau reflète l'ensemble des données chargées dans la carte courante.",
            TABLE_CONTENT_HINT2: "Vous pouvez trier, filtrer selon divers critères, exporter, manipuler la sélection géographique courante et reporter le résultat sur la carte.",
            TABLE_PRINT_WARNING: "Tableau trop lourd pour l'impression",

            ALL_CATEGS:          "Toutes catégories",
            ALL_TERRS:           "Tous territoires",
            OUT_OF_SCOPE:        "hors champ",

            ROWS:           "ligne(s)",
            FILTERED_ROWS:  "lignes filtrées",
            RANGE:          "étendue",
            SEL_VAL:        "Valeur sélection",
            CI:             "Intervalle de confiance" ,

            VALUES_ESTIMATED: "valeurs estimées",
            EXPORT_ESTIM_LABEL: "estimation"
        },

        common: {
            H2_GO_FURTHER:  "ALLER PLUS LOIN",
            ACTIONS:        "ACTIONS",
            GO_TO_WORKSPACE:"Accéder à l'espace",
            GO_TO_WORKSPACE_IN:"Accéder à l'espace Indicateurs" ,
            GO_TO_WORKSPACE_ZO:"Accéder à l'espace Zonages" ,
            GO_TO_WORKSPACE_RE:"Accéder à l'espace Rapports" ,
            GO_TO_WORKSPACE_DI:"Accéder à l'espace Données externes" ,
            SELECT:         "Sélectionner",
            EXPORT:         "Exporter",
            PRINT:          "Imprimer",
            FILTER:         "Filtrer",
            FILTER2:        "Filtre",
            EXEC:           "Exécuter",

            CONFIGURE :     "Configurer",
            DISPLAY_RESTIT: "Afficher la restitution",
            DISPLAY_MAP:    "Afficher la carte",

            YES:            "Oui",
            YES2:            "oui",
            NO:             "Non",
            AUTO:           "auto",
            DELETE:         "Supprimer",
            DELETE_ALL:     "Tout supprimer",
            CHOOSE:         "Choisir",
            CLOSE:          "Fermer",
            CLOSE_PANEL:    "Fermer le panneau",
            CLOSE_PANEL_HINT: "Presser la touche Échap. pour le fermer ultérieurement",
            APPLY:          "Appliquer",
            EXTEND:         "Étendre",

            OK:             "OK",
            OVER:           "sur",
            WHICH_IS:       "soit",
            THE_S:          "les",
            KEY_WORD:       "Mot-clé",
            SEARCH0:        "Recherche",
            SEARCH:         "Rechercher",
            SEARCH2:        "Chercher",
            SEARCHS:        "Recherches",
            START_SEARCH: "Lancer la recherche",
            SEARCH_FAILED:  "Votre recherche n'a pas d'échos",
            CLEAR:          "Effacer",
            EXPORT_SCOPE:   "Champ de l'export",
            EXPORT_PREPARING: "Préparation de l'export en cours",
            DEFINITION:     "Définition",
            REFGEO:         "Référentiel géographique",
            ORIGIN:         "Origine",
            DEST:           "Destination",
            NODATA:         "Absence de données",
            NODATA_DVZ:     "Données manquantes ou insuffisantes pour construire cette dataviz",
            NOGRAPH:        "Graphique non disponible",
            NOGRAPH_REASON_SECRET:     "(secret statistique)",
            NOGRAPH_REASON_NODATA:     "(absence de données)",
            NOGRAPH_REASON_OTHER:      "(données invalides)",

            HELP:           "Aide",
            VALUE:          "Valeur",
            OR:             "ou",
            DATE:           "Date",
            LABEL:          "Libellé",
            WARNING:        "Avertissement",
            NONE_F:         "aucune",
            SAVE:           "Sauver",
            CANCEL:         "Annuler",
            VALIDATE:       "Valider",
            P2:             "&nbsp;:",
            P2B:            " :",

            BEGINS_WITH:    "commence par",
            CONTAINS:       "contient",
            LIST:           "liste",

            BACK:           "Retour",
            COMMENT:        "Commentaire",
            MY_COMMENT :    "Mon commentaire",
            DOC:            "Doc",
            DOCUMENTATION:  "Documentation",
            CHARTS:         "Graphiques",
            FICINDIC:       "Fiche de synthèse",

            AROUND:         "autour de",
            DBL_CLICK:      "Double clic",

            ERROR:          "Erreur",
            TO:             "à",
            SETTINGS:       "Paramètres",
            RESULT:         "Résultat",

            TOTAL:           "Total",
            ENS:            "Ensemble",
            FROM_ENS:       "de l'ensemble",
            IN:             "en",
            BY:             "par",
            FOR:            "pour",
            CODE:           "Code",
            CODES:          "Codes",
            SIMPLE:         "simple",
            DOUBLE:         "double",
            ALL:            "Tous",
            NB_OF:          "Nb de",
            NB:             "Nombre",
            //EFT:            "Effectif",

            FIRST :         "Premier",
            LAST :          "Dernier",

            COMPARISON:     "Comparaison",
            SHORTKEY  :     "Raccourci clavier",
            NEXT :          "suivant",
            PREVIOUS :      "précédent",
            HIDE_CONTROL_PANEL:   "Masquer le panneau de pilotage",
            SHOW_CONTROL_PANEL:   "Afficher le panneau de pilotage",

            CI:             "IC", //intervalle de confiance

            LESS_THAN:      "moins de",
            MORE_THAN:      "plus de",
            MORE_THAN2:     "et plus",

            VERSION:        "Version de Géoclip",

            OPTIONS : "OPTIONS"
        },
        units: {
            KM : "km"
        }
    } ;

    window.GCO5.core.GcLangManager.getInstance().addBundle( lang_o, lang, bundleName );

}(this));
